### ISSUE TITLE
Undefined reference to 'XXX', such as`CheMPS2::Initialize::Init()' while compling test1.cpp

### ISSUE THREAD

**Issue by dingld** [SebWouters/CheMPS2#17]
I succeeded in installing Chemps2 as guided, and "make test" actually went well. But thins went wrong when I complile test1.cpp using icpc. ( the same issue using g++) 
![2015-08-20 22 43 55](https://cloud.githubusercontent.com/assets/13599107/9386393/e238be6a-478d-11e5-9a63-31e312d0408c.png)
![2015-08-20 22 29 40](https://cloud.githubusercontent.com/assets/13599107/9386405/e84a5610-478d-11e5-8917-6fc7b7935340.png)

**Comment by SebWouters** [comment]
Hi,

You need to pass the folder with the include files to the compiler. If you type the following in your build folder, you will see how to:

    make clean
    make VERBOSE=1

On my machine, this gives:

    cd /home/seba/Desktop/CheMPS2_github/build/tests && /opt/intel/composer_xe_2015.0.090/bin/intel64/icpc    -g -O3  -openmp -xHost -ipo -I/home/seba/Desktop/CheMPS2_github/CheMPS2/include/chemps2    -o CMakeFiles/test9.dir/tests/test9.cpp.o -c /home/seba/Desktop/CheMPS2_github/build/tests/tests/test9.cpp

The relevant part for your error is

    -I/home/seba/Desktop/CheMPS2_github/CheMPS2/include/chemps2

I hope this helps! If not or in case you have other questions, let me know!

Best wishes,
Sebastian

**Comment by dingld** [comment]
In the first place I thought the same with you. Then I copied the head files to /usr/include, that is why in the picture above I didn't add include-path. But the compile complains quite similarly.
 I did as you told, and here is what I got. ( I have deleted the head file in /usr/inlcude, and assign path when compiling )
![2015-08-20 23 46 15](https://cloud.githubusercontent.com/assets/13599107/9388172/736dc35a-4796-11e5-8231-342ac719bc68.png)

**Comment by SebWouters** [comment]
Hi,

So if you have installed with

    make install

you either need to specify the headers in your file.ccp as

    #include "chemps2/theheader.h"

instead of

    #include "theheader.h",

or compile with the full header path by passing it to the compiler:

    icpc -g -O3 -openmp -xHost -ipo -fPIC -I/usr/include/chemps2 -o file.o -c file.cpp
    icpc -g -O3 -openmp -xHost -ipo file.o -o mybin -L/usr/lib/x86_64-linux-gnu -lchemps2

Can you try with the exact same order of commands as in the two lines above?

Best wishes,
Sebastian
