### ISSUE TITLE
chemps2 run error

### ISSUE THREAD

**Issue by lucamontana** [SebWouters/CheMPS2#21]
Dear Sebastian, 

when i run psi4.0.5 on the dmrg input file provided in the tutorial in the dmrg directory as you suggest, i obtain the following error 
-------------------------------------------------------
An error has occurred Py-side
Traceback:
<class 'Boost.Python.ArgumentError'>: Python argument types in
    psi4.plugin(str)
did not match C++ signature:
    plugin(std::string, boost::shared_ptr<psi::Wavefunction>):   File "<string>", line 48, in <module>

  File "/home/LUCA/psi-master_18_02.2016/psi4-0.5/share/python/driver.py", line 586, in energy
    wfn = procedures['energy'][lowername](lowername, molecule=molecule, **kwargs)

  File "./../dmrg/pymodule.py", line 52, in run_dmrg
    returnvalue = psi4.plugin('dmrg.so')

-------------------------------------------------------
This is the input file i used in the dmrg directory :

molecule O2 {
  O       0.0   0.0   0.0
  O       0.0   0.0   3.0 
units au
}

sys.path.insert(0, './..')
import dmrg

set basis          cc-pVDZ
set reference      rhf
set scf_type       PK

set dmrg wfn_irrep            0
set dmrg wfn_multp            1
set dmrg frozen_docc          [ 1 , 0 , 0 , 0 , 0 , 1 , 0 , 0 ]
set dmrg active               [ 2 , 0 , 2 , 2 , 0 , 2 , 2 , 2 ]

set dmrg dmrg_states          [   500,  1000,  1000 ]
set dmrg dmrg_e_convergence   [ 1e-10, 1e-10, 1e-10 ]
set dmrg dmrg_maxsweeps       [     5,     5,    10 ]
set dmrg dmrg_noiseprefactors [  0.05,  0.05,   0.0 ]
set dmrg dmrg_print_corr      false
set dmrg dmrg_chkpt           false

set dmrg d_convergence        1e-6
set dmrg dmrg_store_unit      true
set dmrg dmrg_do_diis         true
set dmrg dmrg_diis_branch     1e-2
set dmrg dmrg_store_diis      true

set dmrg dmrg_max_iter        100
set dmrg dmrg_which_root      2   # First excited state
set dmrg dmrg_state_avg       true
set dmrg dmrg_active_space    NO  # INPUT; NO; LOC
set dmrg dmrg_loc_random      false

energy('dmrg')

==========================================================
**Now when i run psi4 on the dmrg input file located somewhere else, i get another error :**

An error has occurred Py-side
Traceback:
<type 'exceptions.ImportError'>: No module named dmrg:   File "<string>", line 27, in <module>

Input file :

molecule H2O {
 0 1
   O   0.000000000   0.00   0.000000000
   H   0.790689766   0.00   0.612217330
   H  -0.790689766   0.00   0.612217330
 units angstrom
}

sys.path.insert(0, '/home/LUCA/psi-master_18_02.2016/psi4-0.5/plugins/mypsi4plugins/dmrg/dmrg.so')
import dmrg

set basis          cc-pVDZ
set reference      rhf
set scf_type       PK
set e_convergence  1e-13
set d_convergence  1e-13
set ints_tolerance 0.0

set dmrg wfn_irrep            0
set dmrg wfn_multp            1
set dmrg frozen_docc          [ 1 , 0 , 0 , 0 ]
set dmrg active               [ 5 , 0 , 4 , 2 ]

set dmrg dmrg_states          [  200,  500, 1000, 1000 ]
set dmrg dmrg_e_convergence   [ 1e-8, 1e-8, 1e-8, 1e-8 ]
set dmrg dmrg_maxsweeps       [    5,    5,    5,  100 ]
set dmrg dmrg_noiseprefactors [ 0.03, 0.03, 0.03,  0.0 ]
set dmrg dmrg_print_corr      false
set dmrg dmrg_chkpt           false

set dmrg dmrg_max_iter        1

energy('dmrg')

==========================================================

**if i change **
sys.path.insert(0, '/home/LUCA/psi-master_18_02.2016/psi4-0.5/plugins/mypsi4plugins/dmrg/dmrg.so')

to  sys.path.insert(0, '/home/LUCA/psi-master_18_02.2016/psi4-0.5/plugins/mypsi4plugins/dmrg')

I get :   
An error has occurred Py-side
Traceback:
<type 'exceptions.ImportError'>: dynamic module does not define init function (initdmrg):   File "<string>", line 27, in <module>

Best wishes
LUCA

ldd ./dmrg.so

	linux-vdso.so.1 (0x00007fff160b3000)
	libchemps2.so.2 => /home/LUCA/psimaster_18_02.2016/CheMPS2/bi/CheMPS2/libchemps2.so.2 (0x00007f2dd0381000)
	libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f2dd005a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f2dcfd5c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f2dcfb46000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2dcf797000)
	libmkl_intel_lp64.so => /home/LUCA/intel_lib/libmkl_intel_lp64.so (0x00007f2dcf050000)
	libmkl_intel_thread.so => /home/LUCA/intel_lib/libmkl_intel_thread.so (0x00007f2dce066000)
	libmkl_core.so => /home/LUCA/intel_lib/libmkl_core.so (0x00007f2dcc987000)
	libiomp5.so => /home/LUCA/intel_lib/libiomp5.so (0x00007f2dcc66f000)
	libhdf5.so.7 => /usr/lib64/libhdf5.so.7 (0x00007f2dcc084000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2dcbe67000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f2dcbc51000)
	libmpi_cxx.so.1 => /usr/lib64/libmpi_cxx.so.1 (0x00007f2dcba36000)
	libmpi.so.1 => /usr/lib64/libmpi.so.1 (0x00007f2dcb68b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f2dcb487000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f2dcb27f000)
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f2dcb066000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f2dcae63000)
	libgomp.so.1 => /usr/lib64/libgomp.so.1 (0x00007f2dcac54000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2dd0947000)

**Comment by SebWouters** [comment]
See also https://github.com/psi4/psi4/issues/266#issuecomment-186113504

The plugin API is clearly wrong. The following is copied from a message above:

     An error has occurred Py-side
     Traceback:
     : Python argument types in
     psi4.plugin(str)
     did not match C++ signature:
     plugin(std::string, boost::shared_ptrpsi::Wavefunction): File "", line 48, in  

     File "/home/LUCA/psi-master_18_02.2016/psi4-0.5/share/python/driver.py", line 586, in energy
     wfn = procedures['energy']lowername

     File "./../dmrg/pymodule.py", line 52, in run_dmrg
     returnvalue = psi4.plugin('dmrg.so')

For the record I copy my file 'pymodule.py' here:

     import psi4
     import re
     import os
     import inputparser
     import math
     import warnings
     from driver import *
     from wrappers import *
     from molutil import *
     import p4util
     from p4xcpt import *


     def run_dmrg(name, **kwargs):
         r"""Function encoding sequence of PSI module and plugin calls so that
         dmrg can be called via :py:func:`~driver.energy`. For post-scf plugins.

         >>> energy('dmrg')

         """
         lowername = name.lower()
         kwargs = p4util.kwargs_lower(kwargs)

         # Your plugin's psi4 run sequence goes here
         #psi4.set_global_option('BASIS', 'sto-3g')
         psi4.set_local_option('MYPLUGIN', 'PRINT', 1)

         # Compute a SCF reference, a wavefunction is return which holds the molecule used, orbitals
         # Fock matrices, and more
         print('Attention! This SCF is density-fitted.')
         ref_wfn = kwargs.get('ref_wfn', None)
         if ref_wfn is None:
             ref_wfn = scf_helper(name, **kwargs)

         # Call the Psi4 plugin
         # Please note that setting the reference wavefunction in this way is ONLY for plugins
         dmrg_wfn = psi4.plugin('dmrg.so', ref_wfn)

         return dmrg_wfn


     # Integration with driver routines
     procedures['energy']['dmrg'] = run_dmrg


     def exampleFN():
         # Your Python code goes here
         pass

As you can see it calls

     dmrg_wfn = psi4.plugin('dmrg.so', ref_wfn)

instead of

     returnvalue = psi4.plugin('dmrg.so')

So have you generated the files \_\_init\_\_.py, pymodule.py etcetera with the right version of psi4 (psi4-0.5)? It doesn't suffice to run the plugin with the right version of psi4, you also need to do

     psi4 --new-plugin dmrg

with the right version of psi4.

Best wishes,
Sebastian

**Comment by SebWouters** [comment]
Hi Luca,

Did this fix your problem?

Best wishes,
Sebastian

**Comment by lucamontana** [comment]
Dear Sebastian, 
As always many thanks for your helps. Really appreciable.

I can easily work with chemps2 binary and it is fantastic, stable, and fast (MPI). 
I wish CASPT2 could be independent of PSI4, and in the binary like state specific CASSCF.

Since i need the dynamical correlation (i still do not know whether it helps me to solve my problem or not)
i switched back to PSI4 to be able to use the newest version of your code (1.7), but however
based on your remarks regarding CASPT2, it is clear CASPT2 is far from being fully ready.
The tutorial regarding CASPT2 misguided me a bit, and i assumed CASPT2 is ready to fire.
And for this reason i switched backed to PSI4.

At this point i just stop the work with PSI4. According to my previous experiences the combination of PSI4 and
CHEMPS2 is not at all stable, as soon as parameter have been set to larger values or larger molecules are taken. It is also much slower than the CHEMPS2 binary.

I need to look for something else concerning dynamical correlation, 
something like DMRG(static)+QMC(dynamic).

ALL THE BEST
LUCA

 
  

Date: Tue, 23 Feb 2016 05:01:24 -0800

**Comment by SebWouters** [comment]
Hi Luca,

I'll take the message that people want to use dmrg-scf and dmrg-caspt2 from the binary. Other people have asked me as well. I'll add it to the binary for v1.7.

Best wishes,
Sebastian

**Comment by SebWouters** [comment]
Hi Luca ( @lucamontana ),

DMRG-SCF and DMRG-CASPT2 are available from the binary now (also with MPI). Soon there should be a manuscript out on the arXiv.

Best wishes,
Sebastian

**Comment by lucamontana** [comment]
Dear Sebastian, 
many many thanks for the notification.I will soon try it out, since i am travelling now.
I will come back to you in case of problems.

Again thanks a lot and best wishesLUCA 

Date: Thu, 28 Apr 2016 07:57:35 -0700
