### ISSUE TITLE
DMRGSCF::construct_gradient

### ISSUE THREAD

**Issue by lucamontana** [SebWouters/CheMPS2#31]
Dear Sebastian, 

For the production run, I get stuck at this point :
-------------------------------------------------------------------------------------------- 
DMRGSCF::construct_gradient : Norm of the gradient = 39.38818667199
--------------------------------------------------------------------------------------------
with no further development.
FCIDUMP is attached :
[FCIDUMP.zip](https://github.com/SebWouters/CheMPS2/files/246370/FCIDUMP.zip)

Does this run for you smoothly to the end ?

Here the input and output :  
--------------------------------
Running chemps2 with the following options:

   FCIDUMP            = FCIDUMP
   GROUP              = cs
   MULTIPLICITY       = 2
   NELECTRONS         = 11
   IRREP              = Ap
   EXCITATION         = 0
   SWEEP_STATES       = [ 20 ]
   SWEEP_ENERGY_CONV  = [ 1e-08 ]
   SWEEP_MAX_SWEEPS   = [ 2 ]
   SWEEP_NOISE_PREFAC = [ 0.05 ]
   SWEEP_DVDSON_RTOL  = [ 1e-10 ]
   NOCC               = [ 2 ; 1 ]
   NACT               = [ 2 ; 2 ]
   NVIR               = [ 25 ; 8 ]
   SCF_STATE_AVG      = FALSE
   SCF_DIIS_THR       = 0
   SCF_GRAD_THR       = 1e-06
   SCF_MAX_ITER       = 100
   SCF_ACTIVE_SPACE   = no additional rotations
   CASPT2_CALC        = TRUE
   CASPT2_ORBS        = as specified in SCF_ACTIVE_SPACE
   CASPT2_IPEA        = 0
   CASPT2_IMAG        = 0
   CASPT2_CHECKPT     = TRUE
   PRINT_CORR         = FALSE
   TMP_FOLDER         = /upb/departments/pc2/scratch/vn05/wouters/cas/c2h3/tmp
 
NORB  = [ 29 , 11 ]
NOCC  = [ 2 , 1 ]
NDMRG = [ 2 , 2 ]
NVIRT = [ 25 , 8 ]
DMRGSCF::setupStart : Number of variables in the x-matrix = 130

   CheMPS2: a spin-adapted implementation of DMRG for ab initio quantum chemistry
   Copyright (C) 2013-2016 Sebastian Wouters

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License along
   with this program; if not, write to the Free Software Foundation, Inc.,
   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

   Stats: nIt(DAVIDSON) = 8
Energy at sites (2, 3) is -52.4503111994477
   Stats: nIt(DAVIDSON) = 8
Energy at sites (1, 2) is -52.4643684612664
******************************************************************
***  Information on left sweep 0 of instruction 0:
***     Elapsed wall time        = 0.012333 seconds
***       |--> S.join            = 9.5e-05 seconds
***       |--> S.solve           = 0.002648 seconds
***       |--> S.split           = 0.000428 seconds
***       |--> Tensor update     = 0.00913 seconds
***              |--> create     = 0.000179 seconds
***              |--> destroy    = 4.2e-05 seconds
***              |--> disk write = 0.005951 seconds
***              |--> disk read  = 0.002636 seconds
***              |--> calc       = 0.000319 seconds
***     Disk write bandwidth     = 0.0871784285204167 MB/s
***     Disk read  bandwidth     = 0.124455221867887 MB/s
***     Minimum energy           = -52.4643684612664
***     Maximum discarded weight = 0
******************************************************************
   Stats: nIt(DAVIDSON) = 1
Energy at sites (0, 1) is -52.4643684612664
   Stats: nIt(DAVIDSON) = 1
Energy at sites (1, 2) is -52.4643684612664
******************************************************************
***  Information on right sweep 0 of instruction 0:
***     Elapsed wall time        = 0.010399 seconds
***       |--> S.join            = 3.6e-05 seconds
***       |--> S.solve           = 0.000261 seconds
***       |--> S.split           = 0.000139 seconds
***       |--> Tensor update     = 0.009945 seconds
***              |--> create     = 0.000172 seconds
***              |--> destroy    = 2.5e-05 seconds
***              |--> disk write = 0.006904 seconds
***              |--> disk read  = 0.002747 seconds
***              |--> calc       = 9.1e-05 seconds
***     Disk write bandwidth     = 0.0475179555103925 MB/s
***     Disk read  bandwidth     = 0.188860148571169 MB/s
***     Minimum energy           = -52.4643684612664
***     Maximum discarded weight = 0
***     Energy difference with respect to previous leftright sweep = 52.4643684612664
******************************************************************
   Stats: nIt(DAVIDSON) = 1
Energy at sites (2, 3) is -52.4643684612664
   Stats: nIt(DAVIDSON) = 1
Energy at sites (1, 2) is -52.4643684612664
******************************************************************
***  Information on left sweep 1 of instruction 0:
***     Elapsed wall time        = 0.010106 seconds
***       |--> S.join            = 4e-05 seconds
***       |--> S.solve           = 0.000271 seconds
***       |--> S.split           = 0.000158 seconds
***       |--> Tensor update     = 0.009622 seconds
***              |--> create     = 0.000174 seconds
***              |--> destroy    = 3.5e-05 seconds
***              |--> disk write = 0.006844 seconds
***              |--> disk read  = 0.00245 seconds
***              |--> calc       = 0.000115 seconds
***     Disk write bandwidth     = 0.075803452385301 MB/s
***     Disk read  bandwidth     = 0.133903659119898 MB/s
***     Minimum energy           = -52.4643684612664
***     Maximum discarded weight = 0
******************************************************************
   Stats: nIt(DAVIDSON) = 1
Energy at sites (0, 1) is -52.4643684612664
   Stats: nIt(DAVIDSON) = 1
Energy at sites (1, 2) is -52.4643684612664
******************************************************************
***  Information on right sweep 1 of instruction 0:
***     Elapsed wall time        = 0.010087 seconds
***       |--> S.join            = 4e-05 seconds
***       |--> S.solve           = 0.000277 seconds
***       |--> S.split           = 0.000117 seconds
***       |--> Tensor update     = 0.009637 seconds
***              |--> create     = 0.000171 seconds
***              |--> destroy    = 3.7e-05 seconds
***              |--> disk write = 0.006625 seconds
***              |--> disk read  = 0.002712 seconds
***              |--> calc       = 9e-05 seconds
***     Disk write bandwidth     = 0.0495190890330189 MB/s
***     Disk read  bandwidth     = 0.191297502995944 MB/s
***     Minimum energy           = -52.4643684612664
***     Maximum discarded weight = 0
***     Energy difference with respect to previous leftright sweep = 0
******************************************************************
***  Information on completed instruction 0:
***     The reduced virtual dimension DSU(2)               = 20
***     Minimum energy encountered during all instructions = -52.4643684612664
***     Minimum energy encountered during the last sweep   = -52.4643684612664
***     Maximum discarded weight during the last sweep     = 0
******************************************************************
********************************************
***  2-RDM and Correlations calculation  ***
********************************************
   N(N-1)                     = 20
   Double trace of DMRG 2-RDM = 20
   Econst + 0.5 * trace(2DM-A * Ham) = -52.4643684612664
   NOON of irrep Ap = [ 1.00000012208089 , 5.82126944224937e-05 ].
   NOON of irrep App = [ 1.99999805028893 , 1.99994361493576 ].
   Single-orbital entropies (Hamiltonian index order is used!) = [ 0.805645305255204 , 1.09467811016217 , 0.000326680798038596 , 6.77546791961997e-05 ].
   Idistance(0) = 1.20757014030603
   Idistance(1) = 1.20809502426363
   Idistance(2) = 1.20924174944415
***************************************************
***  Timing information 2-RDM and Correlations  ***
***************************************************
***     Elapsed wall time        = 0.043281 seconds
***       |--> MPS gauge change  = 0.000236 seconds
***       |--> Diagram calc      = 0.00043 seconds
***       |--> Tensor update     = 0.042511 seconds
***              |--> create     = 0.000664 seconds
***              |--> destroy    = 0.000161 seconds
***              |--> disk write = 0.029186 seconds
***              |--> disk read  = 0.011963 seconds
***              |--> calc       = 0.00051 seconds
***     Disk write bandwidth     = 0.0925377120558658 MB/s
***     Disk read  bandwidth     = 0.225763242001379 MB/s
***************************************************
Info on DMRG::operators rm call to system: 0
DMRGSCF::construct_gradient : Norm of the gradient = 39.38818667199

Best wishes
LUCA

**Comment by SebWouters** [comment]
Hi Luca,

I have the following gradient norms:

run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.876688505054084
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.266382422680337
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.127004291453822
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.0138907822551391
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.0137411766845942
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00505157845425179
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00246916813796708
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00104174755393303
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000424477134387073
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000349434678300792
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000413152555176761
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000461858296688602
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000491602045971536
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000517346745265398
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000547306824951182
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000588173016854287
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000646532353471788
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.0007304923722383
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000851582917099516
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00102725313254958
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00128362638381915
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00165436642157886
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00215406655671265
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00265823907331252
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00271885360074455
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00200296887371174
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.00109806172818592
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000550139115111239
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000282397438162994
run1:DMRGSCF::construct_gradient : Norm of the gradient = 0.000149867998137465
run1:DMRGSCF::construct_gradient : Norm of the gradient = 8.09810039125512e-05
run1:DMRGSCF::construct_gradient : Norm of the gradient = 4.41060256374387e-05
run1:DMRGSCF::construct_gradient : Norm of the gradient = 2.41045881302051e-05
run1:DMRGSCF::construct_gradient : Norm of the gradient = 1.31938860204241e-05
run1:DMRGSCF::construct_gradient : Norm of the gradient = 7.22707254763987e-06
run1:DMRGSCF::construct_gradient : Norm of the gradient = 3.96012354316257e-06
run1:DMRGSCF::construct_gradient : Norm of the gradient = 2.17033089873161e-06
run1:DMRGSCF::construct_gradient : Norm of the gradient = 1.18959025037342e-06
run1:DMRGSCF::construct_gradient : Norm of the gradient = 6.52027602476887e-07

And I get the following CASSCF, CASPT2 and total energies:

E(CASSCF) = -76.8364734676616

CASPT2 : Deviation from pseudocanonical = 0.454660864489553
No file /tmp/CheMPS2_eri_temp.h5 found.
CASPT2 : Deviation from pseudocanonical = 3.42888622394018e-15
CASPT2 : Old size V_SD space  = 16900
CASPT2 : New size V_SD space  = 16351
CASPT2 : Minimum(diagonal)    = 0.0152138472902235
CASPT2 : Number of iterations = 71
CASPT2 : Residual norm        = 9.3241389640271e-11
CASPT2 : Reference weight     = 0.903166541881302
CASPT2 : E2 [DIAGONAL]        = -0.0432267729147062
CASPT2 : E2 [NON-VARIATIONAL] = -0.0440949621872038
CASPT2 : E2 [VARIATIONAL]     = -0.044094962186382
**E_CASSCF + E_CASPT2 = E_0 + E_1 + E_2 = -76.880568429848**

Did you remove all checkpoint files from the previous calculations? ("rm *.h5")

Attached is the full output: [run1.txt](https://github.com/SebWouters/CheMPS2/files/246568/run1.txt)

Best wishes,
Sebastian

**Comment by lucamontana** [comment]
Dear Sebastian, 

many thanks. I simply get stuck at the first gradient point. 
I think this is a problem of the cluster, and not related to the code.

Bests
LUCA
