### ISSUE TITLE
About PyCheMPS2

### ISSUE THREAD

**Issue by Luyoucai** [SebWouters/CheMPS2#33]
Hi, I have encounter a problem when compiling the PyCheMPS2:
I have compiled the CheMPS2 in /home/lujb/usr successfully, then I do:
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/lujb/usr/lib/x86-64gnu
export CPATH=${CPATH}:/home/lujb/usr/include
python setup.py build_ext -L${LD_LIBRARY_PATH} 
A problem occurs:
g++ -pthread -shared build/temp.linux-x86_64-2.7/PyCheMPS2.o -L/home/scicons/openmpi-1.6.5_intel/lib -L/opt/intel/composer_xe_2015.1.133/compiler/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/mpirt/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/ipp/../compiler/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/ipp/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/compiler/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/mkl/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/tbb/lib/intel64/gcc4.4 -L/home/lujb/usr/lib -L/home/scicons/g09/ -L/home/scicons/openmpi-1.6.5_intel/lib -L/opt/intel/composer_xe_2015.1.133/compiler/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/mpirt/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/ipp/../compiler/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/ipp/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/compiler/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/mkl/lib/intel64 -L/opt/intel/composer_xe_2015.1.133/tbb/lib/intel64/gcc4.4 -L/home/lujb/usr/lib -L/home/scicons/g09/ -L -L/home/lujb/chemps2/lib64/x86-64gnu -L/home/lujb/usr/lib/x86-64gnu -lchemps2 -o build/lib.linux-x86_64-2.7/PyCheMPS2.so
/usr/bin/ld: cannot find -lchemps2
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
Then what should I do?

**Comment by SebWouters** [comment]
Hi Luyoucai,

That seems like a strange problem indeed. Just to be certain that the obvious isn't wrong, what does "ls -al /home/lujb/usr/lib/x86-64gnu" return?

Best wishes,
Sebastian

**Comment by Luyoucai** [comment]
It shows that:
ls: cannot access ls: No such file or directory
ls: cannot access /home/lujb/usr/lib/x86-64gnu: No such file or directory

**Comment by Luyoucai** [comment]
I have fixed this problem, thank you!
