### ISSUE TITLE
Cumulant approximation of 4RMD

### ISSUE THREAD

**Issue by quanp** [SebWouters/CheMPS2#36]
Hi Sebastian,

I can see that you already implemented the cumulant approximation of the 4RMD. Is it possible to use it with the binary?

Best regards,
Quan

**Comment by SebWouters** [comment]
Hi Quan,

It is not currently. I found it gave too bad results.

What you can do is comment out the blocks

    for ( int ham_orbz = 0; ham_orbz < nOrbDMRG; ham_orbz++ ){
        if (( next_hamorb1 == ham_orbz ) && ( next_hamorb2 == ham_orbz )){
            ...
        }
    }
    if ( PSEUDOCANONICAL == false ){
        for ( int ham_orb1 = 0; ham_orb1 < nOrbDMRG; ham_orb1++ ){
            for ( int ham_orb2 = ham_orb1 + 1; ham_orb2 < nOrbDMRG; ham_orb2++ ){
                ...
            }
        }
    }

in CASSCFpt2.cpp and replace them with

    CheMPS2::Cumulant::gamma4_fock_contract_ham( Prob, theDMRG->get3DM(), theDMRG->get2DM(), mem2, contract );

I'll add an option in the binary later.

Best wishes,
Sebastian

**Comment by quanp** [comment]
Thanks.

**Comment by SebWouters** [comment]
Hi Quan,

It should be possible now. Let me know if you encounter any bugs.

Best wishes,
Sebastian

**Comment by quanp** [comment]
Hi Sebastian,

Thank you. Now I can see that with cumulant 4RDM, it is much more difficult to converge CASPT2 even using large IMAG. The residual norm during the CASPT2 iteration jumps like crazy, up to 10e+17 in the test14 example.

Best regards,
Quan

**Comment by SebWouters** [comment]
Hi Quan,

I know. I'm not a big fan of it.

There's one caveat though. My CASPT2 equations are solved by diagonalizing
the overlap matrix. When you use a cumulant approximation, you should solve
the generalized eigenvalue problem (i.e. without removing the overlap
matrix). So that's why things become quite bad...

Best wishes,
Sebastian

**Comment by quanp** [comment]
Hi Sebastian,

I added a print command of the residual norm during the CASPT2 iteration and saw that even DMRG-CASPT2 full 4-RDM also has a similar problem like in the cumulant approximation.

For example in https://github.com/quanp/NiFe/blob/master/nife.output
the residual norm oscillated and CASPT2 finished after 2336 iterations! I am not confident if the CASPT2 result is correct.

Another example:
https://github.com/quanp/NiFe/blob/master/cu2.output
the residual norm even oscillated to a greater extent.

Is this problem related to small D or to the CASPT2 algorithm you implemented? I used D = 1000 in all calculations, which should sufficient for an active space of 20-24 orbitals (I think).

Best regards,
Quan

**Comment by SebWouters** [comment]
Hi Quan,

The problem is most likely related to the solution of the CASPT2 equations, which is done with the conjugate gradient algorithm for symmetric positive definite matrices in chemps2. As you can observe by grepping "CASPT2 : Minimum(diagonal)" in both cases you have a negative minimum on the diagonal, resulting most likely in an indefinite matrix.

Basically, what you observe is the breakdown of CASPT2 itself, i.e. that the Fock operator is not a good zeroth order Hamiltonian for ground states, as excitations with negative energies are allowed.

Most likely, the Davidson algorithm would be a better choice to solve the CASPT2 equations in that case. I'll put it on the TODO list.

Can you provide the FCIDUMP and input files?

Best wishes,
Sebastian

**Comment by SebWouters** [comment]
By the way,
What did you print in order to get negative residual 2-norms???

**Comment by quanp** [comment]
Hi Sebastian,

Since I don't know the structure of the program, I just simply add a print in CASPT2.cpp
```
 232    while ( instruction == 'B' ){
 233       matvec( pointers[ 0 ], pointers[ 1 ], diag_fock );
 234       if ( apply_shift ){ add_shift( pointers[ 0 ], pointers[ 1 ], diag_fock, imag_shift, normalizations ); }
 235       instruction = CG.step( pointers );
 236       cout << "CASPT2 : Residual norm        = " << pointers[ 1 ][ 0 ] << endl;
 237    }

```

The FCIDUMP file is very large (21 GB), so I can not send you. But if you have an account in vsc, you can copy it, and the input file.
/scratch/leuven/305/vsc30513/for_seb

Best regards,
Quan

**Comment by quanp** [comment]
FYI, I did the same DMRG-cu(4)-CASPT2 in Molcas (same DMRG reference) and it takes about 21 iterations. 

Best regards,
Quan

**Comment by SebWouters** [comment]
Hi Quan,

1/ The rnorm is only copied in pointers[1][0] at convergence! I.e. on line 135 of https://github.com/SebWouters/CheMPS2/blob/master/CheMPS2/ConjugateGradient.cpp#L135. If you want to print it, the only relevant place is in between lines 127 and 128 of ConjugateGradient.cpp.

2/ I don't have access to /scratch/leuven/305/vsc30513/for_seb from Ghent's gligar computers.

3/ I thought you put CASPT2_CUMUL = FALSE. CheMPS2 always diagonalizes the CASPT2 overlap matrix, which is something you should not do when using the cumulant approximation! So just don't use cu(4) in chemps2 at the moment.

4/ Molcas uses the Davidson algorithm for CASPT2 (I think), and not conjugate gradient. I have put it on the TODO list.

Best wishes,
Sebastian

**Comment by quanp** [comment]
Hi Sebastian,

1/ Thanks for letting me know. 
3/ No, I do not use cu(4) in CheMPS2. I all input files, I used CASPT2_CUMUL = FALSE

Best regards,
Quan

**Comment by SebWouters** [comment]
Hi Quan,

Regarding

1/ You will have figured this one out, but just to restate the obvious again:
Use the rnorm class variable in between lines 127 and 128 of ConjugateGradient.cpp and not pointers[1][0].

2/ I have MOLCAS as well as MOLPRO. So if you give me the input file for MOLCAS and for chemps2, I can generate the FCIDUMP myself.

BTW: Your efforts in testing chemps2 are highly appreciated!

Best wishes,
Sebastian

**Comment by quanp** [comment]
Hi Sebastian,

You can find the input file and the orbital file here:
https://github.com/quanp/NiFe/tree/master/cu2-bis

Thank you for your patience,
Quan

**Comment by quanp** [comment]
Hi Sebastian,

Thank you. I will redo the calculation.

Best regards,
Quan

**Comment by SebWouters** [comment]
Hi Quan,

Just for convenience, to see the progress, you can uncomment line 143 of Davidson.cpp and change it to

    if ( problem_type == 'L' ){ cout << "WARNING AT DAVIDSON : Current residual norm = " << rnorm << endl; }

before starting.

Seb

**Comment by quanp** [comment]
Hi Sebastian,

I have some errors compiling the program as come variables are unidentified.

Best regards,
Quan

```
/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(145): error: identifier "rnorm" is undefined
        if ( rnorm > RTOL ){ // Not yet converged
             ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(172): error: expected a declaration
     if ( state == 'F' ){
     ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(191): warning #12: parsing restarts here after previous syntax error
     return 'D';
               ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(193): error: expected a declaration
  }
  ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(237): warning #12: parsing restarts here after previous syntax error
        Hvecs[ num_allocated ] = new double[ veclength ];
                                                        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(238): error #77: this declaration has no storage class or type specifier
        t_vec = new double[ veclength ];
        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(238): error: identifier "veclength" is undefined
        t_vec = new double[ veclength ];
                            ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(238): error: a value of type "<error-type> *" cannot be used to initialize an entity of type "int"
        t_vec = new double[ veclength ];
                ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(239): error #77: this declaration has no storage class or type specifier
        num_allocated++;
        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(239): error: expected a ";"
        num_allocated++;
                     ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(240): error: expected a declaration
     }
     ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(265): warning #12: parsing restarts here after previous syntax error
     char uplo = 'U';
                    ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(267): error: expected a declaration
     for ( int cnt1 = 0; cnt1 < num_vec; cnt1++ ){
     ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(272): warning #12: parsing restarts here after previous syntax error
     dsyev_( &jobz, &uplo, &num_vec, mxM_vecs, &MAX_NUM_VEC, mxM_eigs, mxM_work, &mxM_lwork, &info ); // Ascending order of eigenvalues
                                                                                                    ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(275): error: expected a declaration
     if ( problem_type == 'L' ){
     ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(312): warning #12: parsing restarts here after previous syntax error
     const double rnorm = FrobeniusNorm( t_vec );
                                                ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(313): error: expected a declaration
     return rnorm;
     ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(315): error: expected a declaration
  }
  ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(377): warning #12: parsing restarts here after previous syntax error
        char trans  = 'T';
                         ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(381): error #77: this declaration has no storage class or type specifier
        dgemm_( &trans, &notr, &NUM_VEC_KEEP, &NUM_VEC_KEEP, &veclength, &one, Reortho_Eigenvecs, &veclength, Reortho_Eigenvecs, &veclength, &zero, Reortho_Overlap, &NUM_VEC_KEEP );
        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(381): error: declaration is incompatible with "void dgemm_(char *, char *, int *, int *, int *, double *, double *, int *, double *, int *, double *, double *, int *)" (declared at line 32 of "/home/quan/source/CheMPS2/CheMPS2/include/chemps2/Lapack.h")
        dgemm_( &trans, &notr, &NUM_VEC_KEEP, &NUM_VEC_KEEP, &veclength, &one, Reortho_Eigenvecs, &veclength, Reortho_Eigenvecs, &veclength, &zero, Reortho_Overlap, &NUM_VEC_KEEP );
        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(381): error: identifier "trans" is undefined
        dgemm_( &trans, &notr, &NUM_VEC_KEEP, &NUM_VEC_KEEP, &veclength, &one, Reortho_Eigenvecs, &veclength, Reortho_Eigenvecs, &veclength, &zero, Reortho_Overlap, &NUM_VEC_KEEP );
                 ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(381): error: expected a ")"
        dgemm_( &trans, &notr, &NUM_VEC_KEEP, &NUM_VEC_KEEP, &veclength, &one, Reortho_Eigenvecs, &veclength, Reortho_Eigenvecs, &veclength, &zero, Reortho_Overlap, &NUM_VEC_KEEP );
                      ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(386): error: variable "info" has already been defined
        int info;
            ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(387): error #77: this declaration has no storage class or type specifier
        dsyev_( &jobz, &uplo, &NUM_VEC_KEEP, Reortho_Overlap, &NUM_VEC_KEEP, Reortho_Overlap_eigs, mxM_work, &mxM_lwork, &info ); // Ascending order of eigs
        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(387): error: declaration is incompatible with "void dsyev_(char *, char *, int *, double *, int *, double *, double *, int *, int *)" (declared at line 35 of "/home/quan/source/CheMPS2/CheMPS2/include/chemps2/Lapack.h")
        dsyev_( &jobz, &uplo, &NUM_VEC_KEEP, Reortho_Overlap, &NUM_VEC_KEEP, Reortho_Overlap_eigs, mxM_work, &mxM_lwork, &info ); // Ascending order of eigs
        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(387): error: a value of type "char *" cannot be used to initialize an entity of type "int"
        dsyev_( &jobz, &uplo, &NUM_VEC_KEEP, Reortho_Overlap, &NUM_VEC_KEEP, Reortho_Overlap_eigs, mxM_work, &mxM_lwork, &info ); // Ascending order of eigs
                ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(387): error: expected a ")"
        dsyev_( &jobz, &uplo, &NUM_VEC_KEEP, Reortho_Overlap, &NUM_VEC_KEEP, Reortho_Overlap_eigs, mxM_work, &mxM_lwork, &info ); // Ascending order of eigs
                     ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(388): error: expected a declaration
        for ( int icnt = 0; icnt < NUM_VEC_KEEP; icnt++ ){
        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(392): warning #12: parsing restarts here after previous syntax error
        dgemm_( &notr, &trans, &NUM_VEC_KEEP, &NUM_VEC_KEEP, &NUM_VEC_KEEP, &one, Reortho_Overlap, &NUM_VEC_KEEP, Reortho_Overlap, &NUM_VEC_KEEP, &zero, Reortho_Lowdin, &NUM_VEC_KEEP );
                                                                                                                                                                                        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(395): error: expected a declaration
        for ( int ivec = 0; ivec < NUM_VEC_KEEP; ivec++ ){
        ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(403): warning #12: parsing restarts here after previous syntax error
     num_vec = 0;
                ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(405): error: expected a declaration
  }
  ^

/home/quan/source/CheMPS2/CheMPS2/Davidson.cpp(428): warning #12: parsing restarts here after previous syntax error
```

**Comment by quanp** [comment]
Sorry,

It works now.

**Comment by quanp** [comment]
Hi Sebastian,

The Davidson significantly improve the convergence! 
For two very similar systems:

System 1: with positive on the diagonal
```
CASPT2 : Minimum(diagonal)    = 0.25482860789996
WARNING AT DAVIDSON : Current residual norm = 0.83724999021524
WARNING AT DAVIDSON : Current residual norm = 0.155961868592507
WARNING AT DAVIDSON : Current residual norm = 0.0502541476650896
WARNING AT DAVIDSON : Current residual norm = 0.0186856579095495
WARNING AT DAVIDSON : Current residual norm = 0.0108784752455047
WARNING AT DAVIDSON : Current residual norm = 0.00429117433767792
WARNING AT DAVIDSON : Current residual norm = 0.00160181567139707
WARNING AT DAVIDSON : Current residual norm = 0.000490439329135126
WARNING AT DAVIDSON : Current residual norm = 0.000183300389806438
WARNING AT DAVIDSON : Current residual norm = 6.04448504055313e-05
WARNING AT DAVIDSON : Current residual norm = 2.05100367877492e-05
WARNING AT DAVIDSON : Current residual norm = 6.272784845903e-06
WARNING AT DAVIDSON : Current residual norm = 2.41765518846668e-06
WARNING AT DAVIDSON : Current residual norm = 8.6668447153295e-07
WARNING AT DAVIDSON : Current residual norm = 3.83068338670776e-07
WARNING AT DAVIDSON : Current residual norm = 1.53524739384666e-07
WARNING AT DAVIDSON : Current residual norm = 5.86233868089383e-08
WARNING AT DAVIDSON : Current residual norm = 2.22050640770074e-08
WARNING AT DAVIDSON : Current residual norm = 8.24086718097205e-09
WARNING AT DAVIDSON : Current residual norm = 2.62445476782879e-09
WARNING AT DAVIDSON : Current residual norm = 1.00601223230246e-09
WARNING AT DAVIDSON : Current residual norm = 3.19548658819277e-10
WARNING AT DAVIDSON : Current residual norm = 1.18639431672864e-10
WARNING AT DAVIDSON : Current residual norm = 3.91083413433088e-11
CASPT2 : Number of iterations = 24

```

System2: with a very negative diagonal. Convergence is slower, but still acceptable, since Conjugate Gradient never works.
```
CASPT2 : Minimum(diagonal)    = -434932.413121927
WARNING AT DAVIDSON : Current residual norm = 9.42683198331322
WARNING AT DAVIDSON : Current residual norm = 9.42461060121697
WARNING AT DAVIDSON : Current residual norm = 9.40721675385909
WARNING AT DAVIDSON : Current residual norm = 8.870627172599
WARNING AT DAVIDSON : Current residual norm = 1.57531957711348
WARNING AT DAVIDSON : Current residual norm = 4.06400132928249
WARNING AT DAVIDSON : Current residual norm = 1.49639582912013
WARNING AT DAVIDSON : Current residual norm = 1.52459765725184
WARNING AT DAVIDSON : Current residual norm = 1.09228449773699
WARNING AT DAVIDSON : Current residual norm = 2.14155431221016
WARNING AT DAVIDSON : Current residual norm = 0.889756072429898
WARNING AT DAVIDSON : Current residual norm = 0.89104270396095
WARNING AT DAVIDSON : Current residual norm = 0.897884293011258

...

WARNING AT DAVIDSON : Current residual norm = 1.38065359540706e-10
WARNING AT DAVIDSON : Current residual norm = 1.38102780919229e-10
WARNING AT DAVIDSON : Current residual norm = 1.75538525814261e-10
WARNING AT DAVIDSON : Current residual norm = 1.95120023749531e-10
WARNING AT DAVIDSON : Current residual norm = 8.92989047176124e-11
CASPT2 : Number of iterations = 846
```
 
Best regards,
Quan

**Comment by SebWouters** [comment]
Hi Quan,

And does it converge to the right answer? It converges the linear system Ax
= b of course, but are A and b sufficiently accurate? Because I have a
special way to compute the 4-RDM, it might be that D should be a little bit
larger. Perhaps it's not a bad idea to check how the energies change by
going from D=1000 to D=1500...

When you use D=1000 for DMRG-SCF, do you then also extrapolate to D =
infinity?

Best wishes,
Sebastian

**Comment by quanp** [comment]
Hi Sebastian,

I plan to increase D too. But this might take some time. I will inform you when I have some numbers.

Best regards,
Quan
