### ISSUE TITLE
Clarify meaning of natural orbitals for active space

### ISSUE THREAD

**Issue by susilehtola** [SebWouters/CheMPS2#41]
The manual states natural orbitals as a choice of the orbital basis
http://sebwouters.github.io/CheMPS2/dmrgscfcalcs.html?highlight=natural

but it doesn't say anything about what kind of natural orbitals these are.

**Comment by SebWouters** [comment]
Hi Susi,

In DMRG-SCF you have multiple DMRG calculations, each for slightly rotated orbitals. When you put the active space orbitals to NO, as you highlighted, it means that you rotate the active space orbitals to NO just after the DMRG calculation (when you know the wavefunction) and just before the orbital rotation gradient and Hessian calculation. For the next DMRG calculation, these orbitals are then reasonably close to the corresponding new NO. A measure for the deviation could be the orbital rotation update norm.

Does this answer your question?

This option was mainly included to play with the active space. Say you want to perform an initial active space selection, but have no clue what it should be. You can perform a very approximate (small virtual dimension) DMRG-SCF calculation with only 1 iteration and a very large active space around the Fermi level, and ask to rotate the active space orbitals to NO. Based on their shape and NOON you can then select a smaller active space, for which you perform subsequent DMRG-SCF calculations.

http://arxiv.org/abs/1405.5642

Best wishes,
Sebastian

**Comment by susilehtola** [comment]
Hi again,

yes, that does clarify the option. From your description, it seems this only affects SCF calculations. You might want to consider including the information you just gave me in the manual :) Thanks!
