### ISSUE TITLE
NOONs printed out

### ISSUE THREAD

**Issue by susilehtola** [SebWouters/CheMPS2#44]
Dear Sebastian,

if I run a calculation with a convergence scheme similar to the one in the documentation
 http://sebwouters.github.io/CheMPS2/inoutput.html
what density matrix will be used to calculate the NOONs? I assume it will be the last one instead of the most accurate one, could you confirm this?

**Comment by SebWouters** [comment]
Hi Susi,

Yes I can confirm this. For RDM-based properties such as the orbital rotation gradient, the orbital rotation Hessian, correlation functions, or NOON, it is best to stop at the largest value of D.

I will copy a piece from http://sebwouters.github.io/CheMPS2/dmrgscfcalcs.html#chemps2-casscf here:

> For DMRG-SCF calculations, the number of reduced virtual basis states should not be decreased in the CheMPS2::ConvergenceScheme object. It is however advised to perform a few sweeps without noise and with very small residual norm tolerance (1e-8 to 1e-10) at the largest value of DSU(2). When you want to extrapolate the energy in the converged active space, it is better to create an orbital rotation checkpoint, and restart the DMRG-SCF calculation for one iteration (MaxIterations_in==1) with a different CheMPS2::ConvergenceScheme.

Best wishes,
Sebastian
