### ISSUE TITLE
CASSCFnewtonraphson.cpp:66]: (style) Redundant condition

### ISSUE THREAD

**Issue by dcb314** [SebWouters/CheMPS2#46]
heMPS2-1.7.3/CheMPS2/CASSCFnewtonraphson.cpp:66]: (style) Redundant condition: OptScheme==0. 'OptScheme!=0 || (OptScheme==0 && rootNum==1)' is equivalent to 'OptScheme!=0 || rootNum==1'

**Comment by SebWouters** [comment]
Hi @dcb314,

You're probably right, but it takes virtually zero CPU time, and most
likely the compiler will resolve this one.

I'm on holiday now, in the middle of nowhere. I will adjust it this weekend
when I'm back :-).

Best wishes,
Sebastian
