### ISSUE TITLE
Oscillator strength

### ISSUE THREAD

**Issue by lucamontana** [SebWouters/CheMPS2#47]
Dear Sebastian, 

Can you tell me how to calculate dmrg oscillator strength 
of the excited states from 1-rdm ? I need to calculate dmrg optical spectrum.

Is there any possibility to plot dmrg orbitals and spin densities of excited states ?

Best wishes
LUCA

**Comment by SebWouters** [comment]
Hi @lucamontana,

I've also added @loriab to the conversation.

What exactly do you mean with oscillator strengths?

The 1-RDM and spin-densities are accessible via

    double CheMPS2::TwoDM::get1RDM_HAM( const int cnt1, const int cnt2 ) const;
    double CheMPS2::TwoDM::spin_density_ham( const int cnt1, const int cnt2 ) const;

respectively, but are currently not (both) interfaced via psi4.

Best wishes,
Sebastian

**Comment by lucamontana** [comment]
Dear Sebastian, 

I mean transition probability for an excited state : https://en.wikipedia.org/wiki/Oscillator_strength .
I have no clue how to calculate it from 1-rdm ? 
I am further interested how an excited state is composed of orbitals.
example : S1 :    homo -> lumo ; homo -1 -> lumo 
                 S2 :    homo -> lumo+1 ; homo -1 -> lumo+1
                 ....
How can i get this piece of information from rmd ?

I am using the binary only. 
Is spin density in a cube file format available through binary ?

Best wishes
LUCA

**Comment by SebWouters** [comment]
@lucamontana,

It's the *transition* 1-RDM (between the ground and excited states) you need to contract with the dipole moment.

The transition 1-RDM is not accessible in v1.7 via the binary, although it can potentially be obtained via the Hylleraas functional. *If* it will become available, it will be from v1.8 or later, so not at the moment.

Also the spin-density is not accessible from the binary in v1.7, only via the library.

Best wishes,
Sebastian

**Comment by lucamontana** [comment]
Dear Sebastian, 

Ok, it seems i have to simply calculate transition 1-rdm between the ground and that particular excited state in which i am interested, and then sum up all contributions to get the total oscillator strength.

Is there any possibility to find out the nature of excited states (i mean its orbital composition : homo -> lumo, etc ...) ?

Bests
LUCA

**Comment by SebWouters** [comment]
> Is there any possibility to find out the nature of excited states (i mean its orbital composition : homo -> lumo, etc ...) ?

Yes. You can look at the occupation numbers in the molecular orbitals (diagonal elements of the 1-particle reduced density matrix in the MO basis)...

**Comment by lucamontana** [comment]
OK,  many thanks Sebastian. 
Take care.
LUCA
