### ISSUE TITLE
How to use CHEMPS2 with OpenMolcas?

### ISSUE THREAD

**Issue by Hassenky** [SebWouters/CheMPS2#61]
Dear Sebastian,

The CHEMPS2 interface is available in OpenMolcas. However, there is no instruction on how to use CHEMPS2 with OpenMolcas right now. Could you please suggest me some basic keywords to use this interface or how to obtain FCIDUMP file through this interface and then I can use CHEMPS2 as a standalone DMRG-CASPT2 implementation?

Thank you very much.

Hassenky

**Comment by quanp** [comment]
Hi,

First you should install both CheMPS2 and OpenMolcas with the interface.
I wrote an instruction for this here:
https://molcas.gitlab.io/doc/sphinx/installation.guide/dmrginst.html

There are two tests you can try DMRG-CASPT2 and learn the basis keywords:
https://gitlab.com/Molcas/OpenMolcas/blob/master/test/grayzone/850.input
https://gitlab.com/Molcas/OpenMolcas/blob/master/test/grayzone/851.input

If you are familiar with Molcas, then doing DMRG with Molcas is very similar, with some extra keywordsin RASSCF and CASPT2 modules.
https://molcas.gitlab.io/doc/sphinx/users.guide/programs/rasscf.html?highlight=dmrg
https://molcas.gitlab.io/doc/sphinx/users.guide/programs/caspt2.html

The FCIDUMP file is always produced in each DMRG iteration so you can obtain it at any time. If you're doing large molecule with large basis set, I suggest **not** to use CheMPS2 as a standalone for DMRG-CASPT2. Use DMRG-CASPT2 in the Molcas interface instead.

Best regards,
Quan

**Comment by Hassenky** [comment]
Thank you so much @quanp. I am reading your instruction.
Hassenky

**Comment by Hassenky** [comment]
Dear @quanp,

I followed all steps you wrote in https://molcas.gitlab.io/doc/sphinx/installation.guide/dmrginst.html. Because OpenMolcas configure file does not support CHEMPS2, Cmake option was used instead. All normal calculations can be done, except from DMRG calculations. I took the 850.input to run DMRG tests; however it seems RASSCF and CASPT2 modules cannot recognize DMRG and ChemPS2 keywords. The output is below. 
[test.log](https://github.com/SebWouters/CheMPS2/files/1415988/test.log)

Could you please give me some tips to surmount such errors?

Kind regards,

Hassenky
