### ISSUE TITLE
Is CheMPS2 still being developed?

### ISSUE THREAD

**Issue by anton-buyskikh** [SebWouters/CheMPS2#72]

**Comment by SebWouters** [comment]
Hi Anton,

Since I've left academia in 2016, there's no active development. Bugs inside CheMPS2 functionality are still handled, and I'm in touch with Quan Phung, who supports the interface to molcas/openmolcas.

May I ask for the reason of your inquiry?

Best regards,
Sebastian

**Comment by anton-buyskikh** [comment]
Hi Sebastian,

Thank you very much for your quick reply! I'm doing a survey of existing packages in quantum chemistry with tensor networks for a potential use in quantum computing. If you know any other alternatives it will be much appreciated.

Cheers,
Anton

**Comment by SebWouters** [comment]
Hi Anton,

Please check Table 2 (page 17) of EPJD paper https://doi.org/10.1140/epjd/e2014-50500-1, which can be retrieved free of charge via e.g. https://www.epj.org/images/stories/news/2014/epj_d_22-09-14.pdf or https://arxiv.org/pdf/1407.2040.pdf.

Best regards,
Sebastian
