### ISSUE TITLE
dyld: lazy symbol binding failed. Strange linking

### ISSUE THREAD

**Issue by dithillobothrium** [SebWouters/CheMPS2#74]
I compiled the library on MacOS. But when I run tests I've got the message

... some initial program output

dyld: lazy symbol binding failed: Symbol not found: _dgeqrf_
  Referenced from: /Users/someuser/Projects/DMRG/chemps2/build/CheMPS2/libchemps2.3.dylib
  Expected in: flat namespace

Another strange thing is that during linking I get the message

ld: warning: directory not found for option '-L/...here all the libraries paths, that are in my ${DYLD_LIBRARY_PATH}'

**Comment by SebWouters** [comment]
Does it detect lapack/blas on building?

On my machine,

    cmake ..

yields (among other output):
 
    -- A library with BLAS API found.
    -- LAPACK detected.
    -- Found TargetLAPACK: Found LAPACK: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libblas.so

And is the library linked against lapack/blas?

On my machine,

    ldd libchemps2.so

yields (among other output):

    liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f35ac3ba000)
    libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f35ac14d000)

According to https://discussions.apple.com/thread/309193 otool -L should be equivalent on mac.

I have no experience at all with mac, so I'm afraid all I can do is ask dr. google as well :-).

**Comment by SebWouters** [comment]
@dithillobothrium 

Were you able to figure it out?

Best regards,
Sebastian
