### ISSUE TITLE
UHF calculation of Open-Shell systems. Spin-dependent FCIDUMP

### ISSUE THREAD

**Issue by dithillobothrium** [SebWouters/CheMPS2#77]
Hello,

Is CheMPS able to read UHF FCIDUMP with integrals calculated with spin-orbitals? Or at least, if the core matrix is spin-dependent. I have a system where I could use ROHF, but the core matrix remains spin-dependent due to external effects.
So I need to read FCIDUMP either as UHF format or in a tricky way, where only the core matrix is stored for both of the spin directions.

Best regrads

**Comment by SebWouters** [comment]
No.

CheMPS2 is tuned for spin-adapted calculations, which requires spin-independent matrix elements. If you use FCIDUMP to input matrix elements, in addition to spin-independence, 8-fold permutation symmetry is also assumed.

Best regards,
Sebastian

**Comment by dithillobothrium** [comment]
Thank you for the answer. 

Not well understood about 8-fold permutation symmetry. Could you please clarify this? 
And, in general, if I have spin-dependent core matrix elements (i j 0 0 indices) - would it be possible to read them correctly for both of the spin directions?

Best,
Ilia

> No.
> 
> CheMPS2 is tuned for spin-adapted calculations, which requires spin-independent matrix elements. If you use FCIDUMP to input matrix elements, in addition to spin-independence, 8-fold permutation symmetry is also assumed.
> 
> Best regards,
> Sebastian

**Comment by SebWouters** [comment]
Sure:

http://vergil.chemistry.gatech.edu/notes/permsymm/permsymm.pdf

If you use chemps2 standalone, and want to do casscf computations, the matrix elements should be spin-independent, i.e. of the ROHF or RHF type.

If you use chemps2 via pyscf, molcas or psi4, only the active space integrals are passed from the program to chemps2. So as long as the effective hamiltonian of the active space, i.e. active space integrals with coulomb and exchange contributions from the core, are spin-independent, i.e. of the  ROHF or RHF type, chemps2 can handle it.

**Comment by dithillobothrium** [comment]
Thank you for the answer.

So, as I understood, it is not possible to use CheMPS2 for my problem, since matrix elements are spin-dependent ?

Best,
Ilia

**Comment by SebWouters** [comment]
Indeed. Your matrix elements are spin-dependent. CheMPS2 can only handle spin-independent matrix elements.
