### ISSUE TITLE
HDF5_C_INCLUDE_DIR-NOTFOUND

### ISSUE THREAD

**Issue by defanet** [SebWouters/CheMPS2#78]
I have tried install HDF5 but this error still show

user@ThinkPad-E495:~/chemlib/chemps2/build$ CXX=g++ cmake .. -DMKL=on -DCMAKE_INSTALL_PREFIX=/usr/local -DWITH_MPI=off -DHDF5_INCLUDE_DIRS=/usr/bin/
-- The CMake build type is Release
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- LAPACK requires BLAS
-- LAPACK detected.
-- HDF5 detected.
-- Configuring done
CMake Error in CheMPS2/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in CheMPS2/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in CheMPS2/CMakeLists.txt:
  Imported target "tgt::hdf5" includes non-existent path

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in CheMPS2/CMakeLists.txt:
  Imported target "tgt::hdf5" includes non-existent path

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

CMake Error in CheMPS2/CMakeLists.txt:
  Found relative path while evaluating include directories of "chemps2-base":

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in CheMPS2/CMakeLists.txt:
  Found relative path while evaluating include directories of "chemps2-base":

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

CMake Error in tests/CMakeLists.txt:
  Target "chemps2-shared" contains relative path in its
  INTERFACE_INCLUDE_DIRECTORIES:

    "HDF5_C_INCLUDE_DIR-NOTFOUND"

-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by SebWouters** [comment]
You don't need any hdf5 binaries for building chemps2, only libraries and headers. Headers are typically in /usr/include/ and not in /usr/bin/. See also http://sebwouters.github.io/CheMPS2/sourcecode.html.

**Comment by SebWouters** [comment]
Did it work out?
