### ISSUE TITLE
Control where temporary files are written

### ISSUE THREAD

**Issue by JFurness1** [SebWouters/CheMPS2#80]
Is it possible to control where PyCheMPS2 writes its temporary files when running through PySCF?

Currently it uses `/tmp/` which has been fine until larger calculations have been filling up this smaller drive. I have larger drives I would like to use for scratch instead.

Is there an environment variable I can set, or option I can pass PyCheMPS2 to change where it writes its scratch files?

Many thanks,
James

**Comment by SebWouters** [comment]
Hi James,

You can set it when creating the python DMRG solver:
https://github.com/SebWouters/CheMPS2/blob/87f787ea74428f6dc27c6a74f16f91e1b3996501/PyCheMPS2/PyCheMPS2.pyx#L133

Does that work out?

Best regards,
Sebastian
